JIRA-8
IgnacioCarazo/apunacub-laboratorio-git pull request #1
Opened 2021-08-18 23:52 UTC by IgnacioCarazo

2021-08-18 23:58 UTC, Cubero2112 commented
Ok

2021-08-18 23:59 UTC, Cubero2112 reviewed
Nice comment

2021-08-18 23:59 UTC, Apu1398 approved these changes
Buen codigo, sigue así

2021-08-19 00:01 UTC, Cubero2112 requested changes
Buen trabajo

2021-08-19 00:04 UTC, Cubero2112 approved these changes
Revisado

2021-08-19 00:05 UTC, merged